apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:05:24Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2726"
  uid: a4efc31c-0312-4c77-a22e-81826b2013a5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.3.137
  clusterIPs:
  - 10.101.3.137
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31987
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
